name: CD Pipeline (Deploy)

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Baixar o artefato gerado no CI
        uses: actions/download-artifact@v4
        with:
          name: site-artifact
          path: site/

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload para o GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/

      - name: Publicar no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4